# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-12 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geodata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(max_length=20, verbose_name='Longitude')),
                ('latitude', models.FloatField(max_length=20, verbose_name='Latitude')),
                ('address', models.TextField(verbose_name='Address')),
            ],
        ),
    ]
